namespace MyBody;

public static class LocalizationService
{
    public static string IdiomaAtual { get; set; } = "pt";

    private static readonly Dictionary<string, Dictionary<string, string>> Dicionario = new()
    {
        ["pt"] = new()
        {
            ["TabDieta"] = "Dieta & Metas",
            ["TabTreino"] = "Fichas de Treino",
            ["TabEvolucao"] = "Evolução",
            ["DadosPessoais"] = "📊 Dados Pessoais & Metas",
            ["Peso"] = "Peso (kg)",
            ["Altura"] = "Altura (cm)",
            ["Idade"] = "Idade",
            ["Sexo"] = "Sexo Biológico",
            ["Atividade"] = "Atividade Física",
            ["CalcularSalvar"] = "Calcular Metas e Salvar",
            ["Hidratacao"] = "💧 Hidratação Diária",
            ["MetaAguaFormat"] = "Meta de água: {0:F2} L / dia ({1:F0} ml)",
            ["InformePeso"] = "Meta de água: Informe seu peso acima",
            ["CalcPeso"] = "Calculado automaticamente (35ml x seu peso)",
            ["ZerarHoje"] = "Zerar Registro de Hoje",
            ["ConsumoCalorico"] = "🍎 Consumo Calórico de Hoje",
            ["TotalCalorias"] = "Total Consumido Hoje: {0:F0} kcal",
            ["RefeicoesDia"] = "Refeições do Dia:",
            ["CadastrarRefeicao"] = "➕ Cadastrar Refeição",
            ["MomentoRefeicao"] = "Momento da Refeição:",
            ["SelecioneAlimento"] = "Selecione o Alimento:",
            ["QtdGramas"] = "Quantidade em Gramas (g):",
            ["QtdUnidades"] = "Quantidade em Unidades:",
            ["AdicionarRefeicao"] = "Adicionar Refeição",

            // Alimentos
            ["Alimento_OvoCozido"] = "Ovo Cozido",
            ["Alimento_OvoMexido"] = "Ovo Mexido",
            ["Alimento_FrangoGrelhado"] = "Peito de Frango Grelhado",
            ["Alimento_ArrozBranco"] = "Arroz Branco",
            ["Alimento_ArrozIntegral"] = "Arroz Integral",
            ["Alimento_FeijaoPreto"] = "Feijão Preto",
            ["Alimento_BatataDoce"] = "Batata Doce",
            ["Alimento_Banana"] = "Banana",
            ["Alimento_Maca"] = "Maçã",
            ["Alimento_Aveia"] = "Aveia em Flocos",
            ["Alimento_Whey"] = "Whey Protein",
            ["Alimento_LeiteAveia"] = "Leite de Aveia",
            ["Alimento_CafeEspresso"] = "Café Espresso",

            // Treinos
            ["MinhaFicha"] = "Minha Ficha de Treino",
            ["AdicionarExercicio"] = "➕ Adicionar Exercício Customizado",
            ["GrupoMuscular"] = "Grupo Muscular:",
            ["NomeExercicio"] = "Nome do Exercício:",
            ["Series"] = "Séries",
            ["Reps"] = "Reps",
            ["Carga"] = "Carga (kg)",
            ["SalvarExercicio"] = "Adicionar a esta Ficha",
            ["ExerciciosSalvos"] = "🏋️ Exercícios do Dia",
            ["SelecaoFicha"] = "📅 Selecione o Dia / Ficha de Treino:",
            ["SemExercicios"] = "Nenhum exercício cadastrado para este treino.",

            // Nomes dos Exercícios
            ["Ex_SupinoReto"] = "Supino Reto com Barra",
            ["Ex_SupinoInclinado"] = "Supino Inclinado com Halteres",
            ["Ex_Crossover"] = "Crossover na Polia",
            ["Ex_TricepsPulley"] = "Tríceps Pulley com Barra W",
            ["Ex_TricepsTesta"] = "Tríceps Testa com Halter",
            ["Ex_PuxadaFrontal"] = "Puxada Frontal",
            ["Ex_RemadaCurvada"] = "Remada Curvada com Barra",
            ["Ex_RemadaBaixa"] = "Remada Baixa Triângulo",
            ["Ex_RoscaDireta"] = "Rosca Direta com Barra W",
            ["Ex_RoscaMartelo"] = "Rosca Martelo com Halteres",
            ["Ex_Agachamento"] = "Agachamento Livre",
            ["Ex_LegPress"] = "Leg Press 45°",
            ["Ex_Extensora"] = "Cadeira Extensora",
            ["Ex_Flexora"] = "Mesa Flexora",
            ["Ex_Panturrilha"] = "Gêmeos em Pé",
            ["Ex_Desenvolvimento"] = "Desenvolvimento com Halteres",
            ["Ex_ElevacaoLateral"] = "Elevação Lateral",
            ["Ex_ElevacaoFrontal"] = "Elevação Frontal na Polia",
            ["Ex_AbdominalInfra"] = "Abdominal Infra na Barra",
            ["Ex_Prancha"] = "Prancha Ventral",
            ["Ex_Esteira"] = "Esteira (Corrida/Caminhada)",
            ["Ex_Burpees"] = "Burpees",
            ["Ex_Kettlebell"] = "Kettlebell Swing",

            // Evolução
            ["TituloEvolucao"] = "📈 Métricas Corporais & Evolução",
            ["ResultadoIMC"] = "IMC: {0:F1} ({1})",
            ["ResultadoTMB"] = "Gasto Calórico Basal (TMB): ~{0:F0} kcal/dia",
            ["GastoTotal"] = "Gasto Energético Total: ~{0:F0} kcal/dia",
            ["HistoricoPeso"] = "📝 Histórico de Peso",
            ["RegistrarNovoPeso"] = "Registrar Novo Peso",
            ["FotosEvolucao"] = "📸 Fotos de Progresso",
            ["SelecionarFoto"] = "Adicionar Foto de Hoje"
        },
        ["en"] = new()
        {
            ["TabDieta"] = "Diet & Goals",
            ["TabTreino"] = "Workout Plans",
            ["TabEvolucao"] = "Progress",
            ["DadosPessoais"] = "📊 Personal Data & Goals",
            ["Peso"] = "Weight (kg)",
            ["Altura"] = "Height (cm)",
            ["Idade"] = "Age",
            ["Sexo"] = "Biological Sex",
            ["Atividade"] = "Physical Activity",
            ["CalcularSalvar"] = "Calculate Goals & Save",
            ["Hidratacao"] = "💧 Daily Hydration",
            ["MetaAguaFormat"] = "Water goal: {0:F2} L / day ({1:F0} ml)",
            ["InformePeso"] = "Water goal: Enter your weight above",
            ["CalcPeso"] = "Automatically calculated (35ml x your weight)",
            ["ZerarHoje"] = "Reset Today's Log",
            ["ConsumoCalorico"] = "🍎 Today's Calorie Intake",
            ["TotalCalorias"] = "Total Consumed Today: {0:F0} kcal",
            ["RefeicoesDia"] = "Today's Meals:",
            ["CadastrarRefeicao"] = "➕ Log Meal",
            ["MomentoRefeicao"] = "Meal Time:",
            ["SelecioneAlimento"] = "Select Food:",
            ["QtdGramas"] = "Quantity in Grams (g):",
            ["QtdUnidades"] = "Quantity in Units:",
            ["AdicionarRefeicao"] = "Add Meal",

            // Foods
            ["Alimento_OvoCozido"] = "Boiled Egg",
            ["Alimento_OvoMexido"] = "Scrambled Egg",
            ["Alimento_FrangoGrelhado"] = "Grilled Chicken Breast",
            ["Alimento_ArrozBranco"] = "White Rice",
            ["Alimento_ArrozIntegral"] = "Brown Rice",
            ["Alimento_FeijaoPreto"] = "Black Beans",
            ["Alimento_BatataDoce"] = "Sweet Potato",
            ["Alimento_Banana"] = "Banana",
            ["Alimento_Maca"] = "Apple",
            ["Alimento_Aveia"] = "Rolled Oats",
            ["Alimento_Whey"] = "Whey Protein",
            ["Alimento_LeiteAveia"] = "Oat Milk",
            ["Alimento_CafeEspresso"] = "Espresso Coffee",

            // Workouts
            ["MinhaFicha"] = "My Workout Routine",
            ["AdicionarExercicio"] = "➕ Add Custom Exercise",
            ["GrupoMuscular"] = "Muscle Group:",
            ["NomeExercicio"] = "Exercise Name:",
            ["Series"] = "Sets",
            ["Reps"] = "Reps",
            ["Carga"] = "Weight (kg)",
            ["SalvarExercicio"] = "Add to this Workout",
            ["ExerciciosSalvos"] = "🏋️ Today's Exercises",
            ["SelecaoFicha"] = "📅 Select Day / Workout Routine:",
            ["SemExercicios"] = "No exercises registered for this workout.",

            // Exercises
            ["Ex_SupinoReto"] = "Barbell Flat Bench Press",
            ["Ex_SupinoInclinado"] = "Incline Dumbbell Press",
            ["Ex_Crossover"] = "Cable Crossover",
            ["Ex_TricepsPulley"] = "Triceps Pushdown (EZ Bar)",
            ["Ex_TricepsTesta"] = "Dumbbell Skullcrusher",
            ["Ex_PuxadaFrontal"] = "Lat Pulldown",
            ["Ex_RemadaCurvada"] = "Barbell Bent-Over Row",
            ["Ex_RemadaBaixa"] = "Seated Cable Row (V-Bar)",
            ["Ex_RoscaDireta"] = "EZ-Bar Biceps Curl",
            ["Ex_RoscaMartelo"] = "Dumbbell Hammer Curl",
            ["Ex_Agachamento"] = "Barbell Squat",
            ["Ex_LegPress"] = "Leg Press 45°",
            ["Ex_Extensora"] = "Leg Extension",
            ["Ex_Flexora"] = "Lying Leg Curl",
            ["Ex_Panturrilha"] = "Standing Calf Raise",
            ["Ex_Desenvolvimento"] = "Dumbbell Shoulder Press",
            ["Ex_ElevacaoLateral"] = "Dumbbell Lateral Raise",
            ["Ex_ElevacaoFrontal"] = "Cable Front Raise",
            ["Ex_AbdominalInfra"] = "Hanging Leg Raise",
            ["Ex_Prancha"] = "Plank",
            ["Ex_Esteira"] = "Treadmill (Run/Walk)",
            ["Ex_Burpees"] = "Burpees",
            ["Ex_Kettlebell"] = "Kettlebell Swing",

            // Progress
            ["TituloEvolucao"] = "📈 Body Metrics & Progress",
            ["ResultadoIMC"] = "BMI: {0:F1} ({1})",
            ["ResultadoTMB"] = "Basal Metabolic Rate (BMR): ~{0:F0} kcal/day",
            ["GastoTotal"] = "Total Daily Energy Expenditure: ~{0:F0} kcal/day",
            ["HistoricoPeso"] = "📝 Weight History",
            ["RegistrarNovoPeso"] = "Log New Weight",
            ["FotosEvolucao"] = "📸 Progress Photos",
            ["SelecionarFoto"] = "Add Today's Photo"
        },
        ["es"] = new()
        {
            ["TabDieta"] = "Dieta y Metas",
            ["TabTreino"] = "Rutinas de Entrenamiento",
            ["TabEvolucao"] = "Evolución",
            ["DadosPessoais"] = "📊 Datos Personales y Metas",
            ["Peso"] = "Peso (kg)",
            ["Altura"] = "Altura (cm)",
            ["Idade"] = "Edad",
            ["Sexo"] = "Sexo Biológico",
            ["Atividade"] = "Actividad Física",
            ["CalcularSalvar"] = "Calcular Metas y Guardar",
            ["Hidratacao"] = "💧 Hidratación Diaria",
            ["MetaAguaFormat"] = "Meta de agua: {0:F2} L / día ({1:F0} ml)",
            ["InformePeso"] = "Meta de agua: Ingrese su peso arriba",
            ["CalcPeso"] = "Calculado automáticamente (35ml x tu peso)",
            ["ZerarHoje"] = "Reiniciar Registro de Hoy",
            ["ConsumoCalorico"] = "🍎 Consumo Calórico de Hoy",
            ["TotalCalorias"] = "Total Consumido Hoy: {0:F0} kcal",
            ["RefeicoesDia"] = "Comidas del Día:",
            ["CadastrarRefeicao"] = "➕ Registrar Comida",
            ["MomentoRefeicao"] = "Momento de la Comida:",
            ["SelecioneAlimento"] = "Seleccionar Alimento:",
            ["QtdGramas"] = "Cantidad en Gramos (g):",
            ["QtdUnidades"] = "Cantidad en Unidades:",
            ["AdicionarRefeicao"] = "Agregar Comida",

            // Alimentos
            ["Alimento_OvoCozido"] = "Huevo Cocido",
            ["Alimento_OvoMexido"] = "Huevo Revuelto",
            ["Alimento_FrangoGrelhado"] = "Pechuga de Pollo a la Plancha",
            ["Alimento_ArrozBranco"] = "Arroz Blanco",
            ["Alimento_ArrozIntegral"] = "Arroz Integral",
            ["Alimento_FeijaoPreto"] = "Frijoles Negros",
            ["Alimento_BatataDoce"] = "Camote / Batata",
            ["Alimento_Banana"] = "Plátano",
            ["Alimento_Maca"] = "Manzana",
            ["Alimento_Aveia"] = "Avena en Copos",
            ["Alimento_Whey"] = "Proteína de Suero (Whey)",
            ["Alimento_LeiteAveia"] = "Leche de Avena",
            ["Alimento_CafeEspresso"] = "Café Esprés",

            // Treinos
            ["MinhaFicha"] = "Mi Rutina de Entrenamiento",
            ["AdicionarExercicio"] = "➕ Agregar Ejercicio Personalizado",
            ["GrupoMuscular"] = "Grupo Muscular:",
            ["NomeExercicio"] = "Nombre del Ejercicio:",
            ["Series"] = "Series",
            ["Reps"] = "Reps",
            ["Carga"] = "Carga (kg)",
            ["SalvarExercicio"] = "Agregar a este Entrenamiento",
            ["ExerciciosSalvos"] = "🏋️ Ejercicios del Día",
            ["SelecaoFicha"] = "📅 Seleccione el Día / Rutina:",
            ["SemExercicios"] = "No hay ejercicios registrados para este entrenamiento.",

            // Ejercicios
            ["Ex_SupinoReto"] = "Press de Banca Plano con Barra",
            ["Ex_SupinoInclinado"] = "Press Inclinado con Mancuernas",
            ["Ex_Crossover"] = "Cruce de Poleas",
            ["Ex_TricepsPulley"] = "Extensión de Tríceps en Polea",
            ["Ex_TricepsTesta"] = "Press Francés con Mancuerna",
            ["Ex_PuxadaFrontal"] = "Jalón al Pecho",
            ["Ex_RemadaCurvada"] = "Remo con Barra",
            ["Ex_RemadaBaixa"] = "Remo Sentado en Polea",
            ["Ex_RoscaDireta"] = "Curl de Bíceps con Barra W",
            ["Ex_RoscaMartelo"] = "Curl Martillo con Mancuernas",
            ["Ex_Agachamento"] = "Sentadilla Libre",
            ["Ex_LegPress"] = "Prensa 45°",
            ["Ex_Extensora"] = "Extensión de Piernas",
            ["Ex_Flexora"] = "Curl Femoral Tumbado",
            ["Ex_Panturrilha"] = "Elevación de Talones de Pie",
            ["Ex_Desenvolvimento"] = "Press de Hombros con Mancuernas",
            ["Ex_ElevacaoLateral"] = "Elevaciones Laterales",
            ["Ex_ElevacaoFrontal"] = "Elevaciones Frontales en Polea",
            ["Ex_AbdominalInfra"] = "Elevación de Piernas en Barra",
            ["Ex_Prancha"] = "Plancha Abdominal",
            ["Ex_Esteira"] = "Cinta de Correr",
            ["Ex_Burpees"] = "Burpees",
            ["Ex_Kettlebell"] = "Kettlebell Swing",

            // Evolución
            ["TituloEvolucao"] = "📈 Métricas Corporales y Evolución",
            ["ResultadoIMC"] = "IMC: {0:F1} ({1})",
            ["ResultadoTMB"] = "Tasa Metabólica Basal (TMB): ~{0:F0} kcal/día",
            ["GastoTotal"] = "Gasto Energético Total: ~{0:F0} kcal/día",
            ["HistoricoPeso"] = "📝 Historial de Peso",
            ["RegistrarNovoPeso"] = "Registrar Nuevo Peso",
            ["FotosEvolucao"] = "📸 Fotos de Progreso",
            ["SelecionarFoto"] = "Agregar Foto de Hoy"
        }
    };

    public static string Get(string chave)
    {
        if (Dicionario.TryGetValue(IdiomaAtual, out var mapa) && mapa.TryGetValue(chave, out var texto))
            return texto;

        return Dicionario["pt"].TryGetValue(chave, out var ptTexto) ? ptTexto : chave;
    }
}